<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
 * Created on April 10 2010
 * Copyright Iain Urquhart www.iain.co.nz
 */
/*
    This file is part of Taxonomy for ExpressionEngine.

    Taxonomy is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Taxonomy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Taxonomy.  If not, see <http://www.gnu.org/licenses/>.
 */


class Taxonomy_upd {

	var $version = '0.22';
	
	function Taxonomy_upd()
	{
		// Make a local reference to the ExpressionEngine super object
		$this->EE =& get_instance();
	}
	

	// --------------------------------------------------------------------

	/**
	 * Module Installer
	 *
	 * @access	public
	 * @return	bool
	 */	
	function install()
	{
		$this->EE->load->dbforge();
		
		$data = array(
			'module_name' => 'Taxonomy' ,
			'module_version' => $this->version,
			'has_cp_backend' => 'y',
			'has_publish_fields' => 'y'
		);

		$this->EE->db->insert('modules', $data);

		// build the taxonomy_trees table
		// this contains keys for each taxonomy_tree_x table generated by the user
		$fields = array(
						'id'		  		=> array(	'type' 			 => 'int',
														'constraint'	 => '10',
														'unsigned'		 => TRUE,
														'auto_increment' => TRUE),
						'label'		  		=> array('type' => 'varchar', 'constraint' => '250'),
						'template_preferences'		=> array('type' => 'varchar', 'constraint' => '250', 'default' => 'all'),
						'channel_preferences'		=> array('type' => 'varchar', 'constraint' => '250', 'default' => 'all')
						);

		$this->EE->dbforge->add_field($fields);
		$this->EE->dbforge->add_key('id', TRUE);
		$this->EE->dbforge->create_table('taxonomy_trees');	
		
		unset($fields);
		
		return TRUE;

	}
	
	
	// --------------------------------------------------------------------

	/**
	 * Module Uninstaller
	 *
	 * @access	public
	 * @return	bool
	 */
	function uninstall()
	{
		$this->EE->load->dbforge();

		$this->EE->db->select('module_id');
		$query = $this->EE->db->get_where('modules', array('module_name' => 'Taxonomy'));

		$this->EE->db->where('module_id', $query->row('module_id'));
		$this->EE->db->delete('module_member_groups');

		$this->EE->db->where('module_name', 'Taxonomy');
		$this->EE->db->delete('modules');
		
		// grab the trees...
		$query = $this->EE->db->get('exp_taxonomy_trees');	
		
		// then drop 'em
		foreach($query->result_array() as $row)
		{
			$this->EE->dbforge->drop_table('taxonomy_tree_'.$row['id']);
		}

		$this->EE->dbforge->drop_table('taxonomy_trees');


		return TRUE;
	}



	// --------------------------------------------------------------------

	/**
	 * Module Updater
	 *
	 * @access	public
	 * @return	bool
	 */	
	
	function update($current='')
	{
		
		return TRUE;
	}
	
}
/* END Class */

/* End of file upd.taxonomy.php */
/* Location: ./system/expressionengine/third_party/modules/nodetree/upd.taxonomy.php */